### ISSUE TITLE
Functions that visualize data for a single repository

### ISSUE THREAD

**Issue by j-tenny** [j-tenny/INF502-Project2#10]
This should be done after issue #6. Some other summary data may also need to be calculated. Ultimately, we need visualize the following:
- [x] A boxplot that compares closed vs. open pull requests in terms of number of commits
- [x] A boxplot that compares closed vs. open pull requests in terms of additions and deletions
- [x] A boxplot that compares the number of changed files grouped by the author association
- [x] A scatterplot that shows the relationship between additions and deletions
- [x] Calculate the correlation between all the numeric data in the pull requests for a repository (and visualize as a matrix?)

We will probably a need a filepath argument in each plotting function. Each function will need the ability to save the plot as a png at the specified filepath.

**Comment by vas235** [comment]
I will start working on these last two

**Comment by j-tenny** [comment]
#28
