### ISSUE TITLE
Summarize user data for a repository

### ISSUE THREAD

**Issue by j-tenny** [j-tenny/INF502-Project2#12]
This should be completed after issue #1. Compile and calculate the correlation between the data fields collected about users of a single github repository
    * following
    * followers
    * number of pull requests
    * number of contributions
    * etc.

**Comment by vas235** [comment]
from Vova's instructions I am only going to calculate and print this correlation data, I won't be outputting it to any files. I will use pandas built in correlation function.

**Comment by j-tenny** [comment]
Finished with PR #22
