### ISSUE TITLE
Subsequent figures get screwed up

### ISSUE THREAD

**Issue by j-tenny** [j-tenny/INF502-Project2#33]
If you download multiple repositories and run the Summarize Repository functions for each one, the first set of figures looks fine, but later figures are messed up. I suspect this is because pyplot is designed for live, interactive usage where the figure stays open and additional commands add to the figure. I think maybe the figures aren't closing and starting fresh before starting the next figure. I tried to find a solution, but couldn't figure it out.

**Comment by vas235** [comment]
Oh I see, did you happen to notice if that was happening with the functions
that used pandas built in graphing methods instead of pyplot?

**Comment by vas235** [comment]
running the whole app from console I am not getting that issue, I did have to fix a type for the output_filepath in the application file and the gitdata file, the only graph that looks weird is the scatterplot something must be wrong with it, but the graphs appear to be saving properly, and they overwrite the identical graph when saving multiple times

**Comment by vas235** [comment]
Ok I got this issue among others fixed, I am pushing to main.

**Comment by j-tenny** [comment]
Fixed with #34
