### ISSUE TITLE
All Repos summary class + data

### ISSUE THREAD

**Issue by j-tenny** [j-tenny/INF502-Project2#4]
Create a class and functions that will use the github API to download summary data for all repositories on github. The class could be called "AllRepoSummary" or whatever you think sounds concise and descriptive. The requirements are unclear about the time scale we should consider. There probably needs to be an argument in the __init__ function that defines the timescale to be considered by this summary. The class should download data from the github API and store it in the class. There should probably be a function that converts the data to a dataframe. Generating the visualizations noted in a separate github issue. 

Download and store the following across all repositories on Github:

   * Total number of pull requests on each date in the time window
   * Number of open pull requests and closed pull requests on each date in the time window
   * Number of users per repository

**Comment by j-tenny** [comment]
In hindsight, it is unclear whether we are supposed to get data for all repositories on github or all repositories that have been downloaded in the session.

**Comment by j-tenny** [comment]
Clarification from Vova:

_So user can enter repos of interest
All these repos of interest must be made into graph on request
And that's for current session
Each session should clear all the info before proceeding
That makes sense?_

**Comment by vas235** [comment]
This should be done and ready

**Comment by j-tenny** [comment]
Solved with pull request #19
