### ISSUE TITLE
Add visualization functions to All Repos Summary

### ISSUE THREAD

**Issue by j-tenny** [j-tenny/INF502-Project2#5]
Issue #4 must be completed first. After that data wrangling is done, need to add functions that create the following visualizations about all repos on github:

   * A line graph showing the total number of pull requests per day
   * A line graph comparing number of open and closed pull requests per day
   * A bars plot comparing the number of users per repository

For each plotting function, probably will need a function argument for "filepath". For each plotting function, we will need the ability to save a .png of the plot to that filepath.

**Comment by j-tenny** [comment]
Pull request #19 contains functionality to "display" these plots but now we need to save them to a file at a specified filepath

**Comment by vas235** [comment]
I will add the .png output to these functions

**Comment by vas235** [comment]
is the user supposed to input a filepath for this or can we just throw all the pngs in a directory "output_pngs"
